### ISSUE TITLE
error enable plugin

### ISSUE THREAD

**Issue by twixi** [MEFRREEX/Whitelister#1]
`2024-08-05 08:51:24.421 [main] INFO  - Ввімкнення  Whitelister v1.4.3
2024-08-05 08:51:24.703 [main] ERROR - Throwing
java.lang.RuntimeException: java.util.concurrent.CompletionException: java.lang.IllegalAccessError: failed to access class com.mysql.cj.conf.ConnectionUrl$1 from class com.mysql.cj.conf.ConnectionUrl (com.mysql.cj.conf.ConnectionUrl$1 is in unnamed module of loader cn.nukkit.plugin.PluginClassLoader @4fbb1144; com.mysql.cj.conf.ConnectionUrl is in unnamed module of loader cn.nukkit.plugin.PluginClassLoader @78c74647)
	at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:440) [nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.Server.enablePlugin(Server.java:755) [nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.Server.enablePlugins(Server.java:744) [nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.Server.<init>(Server.java:587) [nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.Nukkit.main(Nukkit.java:120) [nukkit-1.0-SNAPSHOT.jar:?]
Caused by: java.util.concurrent.CompletionException: java.lang.IllegalAccessError: failed to access class com.mysql.cj.conf.ConnectionUrl$1 from class com.mysql.cj.conf.ConnectionUrl (com.mysql.cj.conf.ConnectionUrl$1 is in unnamed module of loader cn.nukkit.plugin.PluginClassLoader @4fbb1144; com.mysql.cj.conf.ConnectionUrl is in unnamed module of loader cn.nukkit.plugin.PluginClassLoader @78c74647)
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?]
Caused by: java.lang.IllegalAccessError: failed to access class com.mysql.cj.conf.ConnectionUrl$1 from class com.mysql.cj.conf.ConnectionUrl (com.mysql.cj.conf.ConnectionUrl$1 is in unnamed module of loader cn.nukkit.plugin.PluginClassLoader @4fbb1144; com.mysql.cj.conf.ConnectionUrl is in unnamed module of loader cn.nukkit.plugin.PluginClassLoader @78c74647)
	at com.mysql.cj.conf.ConnectionUrl.getConnectionUrlInstance(ConnectionUrl.java:198) ~[?:?]
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:204) ~[?:?]
	at java.sql.DriverManager.getConnection(DriverManager.java:683) ~[java.sql:?]
	at java.sql.DriverManager.getConnection(DriverManager.java:230) ~[java.sql:?]
	at com.mefrreex.jooq.database.MySQLDatabase.lambda$getConnection$0(MySQLDatabase.java:42) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?]
2024-08-05 08:51:24.717 [main] INFO  - Вимкнення Whitelister v1.4.3
2024-08-05 08:51:24.719 [main] ERROR - Throwing
java.lang.NullPointerException: Cannot invoke "com.mefrreex.whitelister.whitelist.WhitelistManager.saveWhitelist()" because "this.whitelistManager" is null
	at com.mefrreex.whitelister.Whitelister.onDisable(Whitelister.java:69) ~[?:?]
	at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:91) ~[nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.plugin.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:132) ~[nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.plugin.PluginManager.disablePlugin(PluginManager.java:510) [nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:442) [nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.Server.enablePlugin(Server.java:755) [nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.Server.enablePlugins(Server.java:744) [nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.Server.<init>(Server.java:587) [nukkit-1.0-SNAPSHOT.jar:?]
	at cn.nukkit.Nukkit.main(Nukkit.java:120) [nukkit-1.0-SNAPSHOT.jar:?]`

**Comment by MEFRREEX** [comment]
Problem solved?

**Comment by twixi** [comment]
yes
